### ISSUE TITLE
Support for @typescript-eslint/*@6.x.x

### ISSUE THREAD

**Issue by tclindner** [tclindner/eslint-config-typescript-tc#665]
[Migration guide](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/)

Dependencies

- [x] https://github.com/jest-community/eslint-plugin-jest/issues/1398
- [x] https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2175

**Comment by pohnemus** [comment]
With this are you thinking of nuking the rules we have and going with one of the presets?

**Comment by tclindner** [comment]
> With this are you thinking of nuking the rules we have and going with one of the presets?

Yep! Just pushed everything I think we can clean up with the rulesets that are offered. Let me know what you think!

**Comment by pohnemus** [comment]
Cool - I like it. Do you expect this to be impactful to consumers due to rule changes?

**Comment by tclindner** [comment]
We had a number of the rules already, so I'm hoping it won't be terrible. There are some more obscure ones that could cause some churn. I'm thinking that we can create a beta and try it out in a few projects to assess impact before we release a stable version. What do you think?
